const Data = [
    { id: 0, name: 'Twitter Clone', desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet, dolor eum ratione molestias laboriosam quis.', img: 'src/assets/imgs/TwitterProject.png', tech: 'HTML , CSS', live: 'https://ahmedsaeed217.github.io/Twitter-Clone/', code: 'https://github.com/AhmedSaeed217/Twitter-Clone', category: 'landing' },
    { id: 1, name: 'Twitter Clone', desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet, dolor eum ratione molestias laboriosam quis.', img: 'src/assets/imgs/YoutubeProject.png', tech: 'HTML , CSS', live: 'https://ahmedsaeed217.github.io/Youtube-Clone/', code: 'https://github.com/AhmedSaeed217/Youtube-Clone', category: 'landing' },
    { id: 2, name: 'Feane Restaurant', desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet, dolor eum ratione molestias laboriosam quis.', img: 'src/assets/imgs/FeaneProject.png', tech: 'HTML , CSS , Bootstrap , JS , Jquery', live: 'https://ahmedsaeed217.github.io/Feane-Food-Restaurant/', code: 'https://github.com/AhmedSaeed217/Feane-Food-Restaurant', category: 'landing' },
    { id: 3, name: 'Product Filter App', desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet, dolor eum ratione molestias laboriosam quis.', img: 'src/assets/imgs/ProductFilterProject.png', tech: 'HTML , CSS , Bootstrap , JS , React', live: 'https://product-filetring-react-app.netlify.app/', code: 'https://github.com/AhmedSaeed217/Product-Filtering-React-App', category: 'React' },
    { id: 4, name: 'Topico', desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet, dolor eum ratione molestias laboriosam quis.', img: 'src/assets/imgs/topicoProject.png', tech: 'HTML , CSS , JS', live: 'https://ahmedsaeed217.github.io/TOPICO/', code: 'https://github.com/AhmedSaeed217/TOPICO', category: 'advanced' },
    { id: 5, name: 'Icloud Store', desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet, dolor eum ratione molestias laboriosam quis.', img: 'src/assets/imgs/CrudProject.png', tech: 'HTML , CSS , JS', live: 'https://ahmedsaeed217.github.io/I-Cloud-Store/', code: 'https://github.com/AhmedSaeed217/I-Cloud-Store', category: 'advanced' },
    { id: 6, name: 'Recipe App', desc: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet, dolor eum ratione molestias laboriosam quis.', img: 'src/assets/imgs/RecipeProject.png', tech: 'HTML , CSS , Bootstrap , JS', live: 'https://recipeappsaeed.netlify.app/', code: 'https://github.com/AhmedSaeed217/RecipeApp', category: 'advanced' },
]

export default Data;